const mongoose = require("mongoose");
require("dotenv").config();

const Product = require("../models/Product");
const Category = require("../models/Category");
const Brand = require("../models/Brand");

const toSlug = (str) =>
  str.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

// Picsum Photos — reliable placeholder images by ID (always works, no auth needed)
// Category-specific image pools mapped by product type
const IMAGE_POOLS = {
  laptop:      ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80","https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&q=80","https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80","https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=600&q=80"],
  phone:       ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80","https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=600&q=80","https://images.unsplash.com/photo-1598327106026-848a11c3e8b3?w=600&q=80","https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&q=80"],
  headphones:  ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80","https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&q=80","https://images.unsplash.com/photo-1520170350707-b2da59970118?w=600&q=80","https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&q=80"],
  tv:          ["https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=600&q=80","https://images.unsplash.com/photo-1571415060716-baff5ea4c1d7?w=600&q=80","https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?w=600&q=80","https://images.unsplash.com/photo-1461151304267-38535e780c79?w=600&q=80"],
  tablet:      ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80","https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?w=600&q=80","https://images.unsplash.com/photo-1623126908029-58cb08a2b272?w=600&q=80","https://images.unsplash.com/photo-1561154464-82e9adf32764?w=600&q=80"],
  smartwatch:  ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80","https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&q=80","https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80","https://images.unsplash.com/photo-1617625785292-eb4e0b27d285?w=600&q=80"],
  camera:      ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80","https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&q=80","https://images.unsplash.com/photo-1471733820775-51f7cf96efab?w=600&q=80","https://images.unsplash.com/photo-1617859047452-8510bcf207fd?w=600&q=80"],
  shoes:       ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80","https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&q=80","https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600&q=80","https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&q=80"],
  clothing:    ["https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&q=80","https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=600&q=80","https://images.unsplash.com/photo-1562157873-818bc0726f68?w=600&q=80","https://images.unsplash.com/photo-1551232864-3f0890e580d9?w=600&q=80"],
  cookware:    ["https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80","https://images.unsplash.com/photo-1584990347449-a2d4c2c044a2?w=600&q=80","https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&q=80","https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=600&q=80"],
  appliance:   ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80","https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80","https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=600&q=80","https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80"],
  book:        ["https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80","https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80","https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80","https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=600&q=80"],
  sports:      ["https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80","https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&q=80","https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=600&q=80","https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&q=80"],
  beauty:      ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80","https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=600&q=80","https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=600&q=80","https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80"],
  grocery:     ["https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80","https://images.unsplash.com/photo-1526470498-9ae73c665de8?w=600&q=80","https://images.unsplash.com/photo-1553546895-531931aa1aa8?w=600&q=80","https://images.unsplash.com/photo-1506617420156-8e4536971650?w=600&q=80"],
  toy:         ["https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80","https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&q=80","https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=600&q=80","https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80"],
  automotive:  ["https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=600&q=80","https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600&q=80","https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&q=80","https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80"],
  furniture:   ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80","https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80","https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80","https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600&q=80"],
};

// Returns [thumbnail, img1, img2, img3, img4] for a given pool key
const imgs = (poolKey) => {
  const pool = IMAGE_POOLS[poolKey] || IMAGE_POOLS.appliance;
  return pool; // first = thumbnail, rest = images array
};

// Unused `img` alias kept for compat
const img = (poolKey) => IMAGE_POOLS[poolKey]?.[0] || "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80";

async function seedProducts() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB connected");

    const categories = await Category.find({ status: true });
    const brands     = await Brand.find({ status: true });

    if (!categories.length || !brands.length) {
      console.error("❌ Run seedCategory.js and seedBrand.js first!");
      process.exit(1);
    }

    const cat   = (slug) => categories.find((c) => c.slug === slug)?._id || categories[0]._id;
    const brand = (slug) => brands.find((b) => b.slug === slug)?._id    || brands[0]._id;

    const products = [
      // ── ELECTRONICS / LAPTOPS ─────────────────────────────────────────────
      {
        name: "Apple MacBook Air M2 13-inch",
        slug: toSlug("Apple MacBook Air M2 13-inch"),
        short_description: "8-core CPU, 8GB RAM, 256GB SSD, Midnight colour",
        description: "The MacBook Air M2 delivers exceptional performance with Apple Silicon, all-day battery life and a stunning Liquid Retina display.",
        category_id: cat("electronics"), subcategory_id: cat("laptops"), brand_id: brand("apple"),
        price: 99900, mrp: 114900, discount_percent: 13, sku: "APPL-MBA-M2-001",
        stock: 40, low_stock_threshold: 5, is_featured: true, is_bestseller: true,
        thumbnail: imgs("laptop")[0],
        images: imgs("laptop"),
        tags: ["laptop","apple","macbook","m2"],
        specifications: [{ key:"Processor",value:"Apple M2 8-core"},{ key:"RAM",value:"8 GB"},{ key:"Storage",value:"256 GB SSD"},{ key:"Display",value:"13.6 inch Liquid Retina"}],
        weight: 1240, rating_avg: 4.8, rating_count: 320, total_sold: 850, status: true,
      },
      {
        name: "Dell XPS 15 Core i7 OLED",
        slug: toSlug("Dell XPS 15 Core i7 OLED"),
        short_description: "Intel i7-13700H, 16GB RAM, 512GB SSD, 3.5K OLED display",
        description: "Dell XPS 15 combines power and portability with a stunning OLED touchscreen and powerful Intel processor.",
        category_id: cat("electronics"), subcategory_id: cat("laptops"), brand_id: brand("dell"),
        price: 149990, mrp: 169990, discount_percent: 12, sku: "DELL-XPS15-001",
        stock: 25, low_stock_threshold: 5, is_featured: true,
        thumbnail: imgs("laptop")[1],
        images: imgs("laptop"),
        tags: ["laptop","dell","xps","oled"],
        specifications: [{ key:"Processor",value:"Intel Core i7-13700H"},{ key:"RAM",value:"16 GB DDR5"},{ key:"Storage",value:"512 GB NVMe SSD"},{ key:"Display",value:"15.6 inch 3.5K OLED"}],
        weight: 1860, rating_avg: 4.6, rating_count: 180, total_sold: 420, status: true,
      },
      {
        name: "HP Pavilion 15 Ryzen 5",
        slug: toSlug("HP Pavilion 15 Ryzen 5"),
        short_description: "AMD Ryzen 5 7520U, 8GB RAM, 512GB SSD, FHD display",
        description: "HP Pavilion 15 is a great everyday laptop with AMD Ryzen 5, fast SSD and vibrant Full HD display.",
        category_id: cat("electronics"), subcategory_id: cat("laptops"), brand_id: brand("hp"),
        price: 54990, mrp: 64990, discount_percent: 15, sku: "HP-PAV15-R5-001",
        stock: 60, low_stock_threshold: 10, is_bestseller: true,
        thumbnail: imgs("laptop")[2],
        images: imgs("laptop"),
        tags: ["laptop","hp","pavilion","ryzen"],
        specifications: [{ key:"Processor",value:"AMD Ryzen 5 7520U"},{ key:"RAM",value:"8 GB DDR5"},{ key:"Storage",value:"512 GB SSD"},{ key:"Display",value:"15.6 inch FHD"}],
        weight: 1750, rating_avg: 4.3, rating_count: 240, total_sold: 670, status: true,
      },
      {
        name: "Lenovo IdeaPad Slim 5 Core i5",
        slug: toSlug("Lenovo IdeaPad Slim 5 Core i5"),
        short_description: "Intel Core i5-1335U, 16GB RAM, 512GB SSD, 14-inch WUXGA",
        description: "IdeaPad Slim 5 offers a sleek design, fast performance and excellent display for work and entertainment.",
        category_id: cat("electronics"), subcategory_id: cat("laptops"), brand_id: brand("lenovo"),
        price: 62990, mrp: 74990, discount_percent: 16, sku: "LEN-IPS5-I5-001",
        stock: 45, low_stock_threshold: 8,
        thumbnail: imgs("laptop")[3],
        images: imgs("laptop"),
        tags: ["laptop","lenovo","ideapad","intel"],
        specifications: [{ key:"Processor",value:"Intel Core i5-1335U"},{ key:"RAM",value:"16 GB DDR4"},{ key:"Storage",value:"512 GB SSD"},{ key:"Display",value:"14 inch WUXGA IPS"}],
        weight: 1500, rating_avg: 4.4, rating_count: 195, total_sold: 530, status: true,
      },
      {
        name: "Asus ROG Strix G15 Gaming Laptop",
        slug: toSlug("Asus ROG Strix G15 Gaming Laptop"),
        short_description: "Ryzen 9 6900HX, RTX 3070 Ti, 16GB RAM, 1TB SSD, 300Hz",
        description: "ASUS ROG Strix G15 is a beast gaming laptop with AMD Ryzen 9 and NVIDIA RTX 3070 Ti for ultra-high frame rates.",
        category_id: cat("electronics"), subcategory_id: cat("laptops"), brand_id: brand("asus"),
        price: 139990, mrp: 159990, discount_percent: 13, sku: "ASUS-ROG-G15-001",
        stock: 20, low_stock_threshold: 3, is_featured: true, is_new_arrival: true,
        thumbnail: imgs("laptop")[0],
        images: imgs("laptop"),
        tags: ["gaming","laptop","asus","rog","rtx"],
        specifications: [{ key:"Processor",value:"AMD Ryzen 9 6900HX"},{ key:"GPU",value:"NVIDIA RTX 3070 Ti"},{ key:"RAM",value:"16 GB DDR5"},{ key:"Display",value:"15.6 inch FHD 300Hz"}],
        weight: 2300, rating_avg: 4.7, rating_count: 280, total_sold: 420, status: true,
      },
      // ── ELECTRONICS / AUDIO & TV ──────────────────────────────────────────
      {
        name: "Sony WH-1000XM5 Wireless Headphones",
        slug: toSlug("Sony WH-1000XM5 Wireless Headphones"),
        short_description: "Industry-leading noise cancelling, 30hr battery, Hi-Res Audio",
        description: "Sony WH-1000XM5 sets the benchmark for noise cancelling headphones with superior sound quality and comfort.",
        category_id: cat("electronics"), subcategory_id: cat("headphones"), brand_id: brand("sony"),
        price: 24990, mrp: 29990, discount_percent: 17, sku: "SONY-WH1000XM5-001",
        stock: 80, low_stock_threshold: 10, is_featured: true, is_bestseller: true,
        thumbnail: imgs("headphones")[0],
        images: imgs("headphones"),
        tags: ["headphones","sony","wireless","noise-cancelling"],
        specifications: [{ key:"Driver",value:"30mm"},{ key:"Battery",value:"30 hours"},{ key:"Connectivity",value:"Bluetooth 5.2"},{ key:"Weight",value:"250g"}],
        weight: 250, rating_avg: 4.9, rating_count: 560, total_sold: 1200, status: true,
      },
      {
        name: "boAt Rockerz 550 Wireless Headphones",
        slug: toSlug("boAt Rockerz 550 Wireless Headphones"),
        short_description: "40mm drivers, 20hr playback, foldable, soft earcushions",
        description: "boAt Rockerz 550 offers immersive sound with 40mm drivers, long battery life and a foldable design.",
        category_id: cat("electronics"), subcategory_id: cat("headphones"), brand_id: brand("samsung"),
        price: 1299, mrp: 3990, discount_percent: 67, sku: "BOAT-R550-001",
        stock: 300, low_stock_threshold: 30, is_bestseller: true,
        thumbnail: imgs("headphones")[1],
        images: imgs("headphones"),
        tags: ["headphones","boat","wireless","budget"],
        specifications: [{ key:"Driver",value:"40mm"},{ key:"Battery",value:"20 hours"},{ key:"Connectivity",value:"Bluetooth 5.0"},{ key:"Foldable",value:"Yes"}],
        weight: 220, rating_avg: 4.2, rating_count: 1800, total_sold: 6000, status: true,
      },
      {
        name: "Samsung 55-inch 4K QLED Smart TV",
        slug: toSlug("Samsung 55-inch 4K QLED Smart TV"),
        short_description: "Quantum Dot, 4K UHD, Tizen OS, HDR10+",
        description: "Samsung QLED TV delivers vivid colours with Quantum Dot technology and smart features via Tizen OS.",
        category_id: cat("electronics"), subcategory_id: cat("televisions"), brand_id: brand("samsung"),
        price: 64990, mrp: 84990, discount_percent: 24, sku: "SAM-QLED55-001",
        stock: 30, low_stock_threshold: 5, is_featured: true,
        thumbnail: imgs("tv")[0],
        images: imgs("tv"),
        tags: ["tv","samsung","qled","4k","smart-tv"],
        specifications: [{ key:"Screen Size",value:"55 inch"},{ key:"Resolution",value:"4K UHD"},{ key:"Panel",value:"QLED"},{ key:"OS",value:"Tizen"}],
        weight: 16500, rating_avg: 4.6, rating_count: 410, total_sold: 780, status: true,
      },
      {
        name: "LG 43-inch Full HD Smart TV",
        slug: toSlug("LG 43-inch Full HD Smart TV"),
        short_description: "webOS, AI ThinQ, Dolby Audio, HDMI x2",
        description: "LG 43-inch smart TV with webOS and AI ThinQ offers a smart entertainment experience at an affordable price.",
        category_id: cat("electronics"), subcategory_id: cat("televisions"), brand_id: brand("lg"),
        price: 28990, mrp: 35990, discount_percent: 19, sku: "LG-TV43-FHD-001",
        stock: 45, low_stock_threshold: 5,
        thumbnail: imgs("tv")[1],
        images: imgs("tv"),
        tags: ["tv","lg","smart-tv","fhd"],
        specifications: [{ key:"Screen Size",value:"43 inch"},{ key:"Resolution",value:"Full HD 1080p"},{ key:"OS",value:"webOS"},{ key:"Audio",value:"Dolby Audio 20W"}],
        weight: 7500, rating_avg: 4.4, rating_count: 360, total_sold: 820, status: true,
      },
      // ── MOBILES / SMARTPHONES ─────────────────────────────────────────────
      {
        name: "Apple iPhone 15 128GB",
        slug: toSlug("Apple iPhone 15 128GB"),
        short_description: "A16 Bionic chip, 48MP camera, Dynamic Island, USB-C",
        description: "iPhone 15 features the powerful A16 Bionic chip, a 48MP main camera system and the all-new Dynamic Island.",
        category_id: cat("mobiles"), subcategory_id: cat("smartphones"), brand_id: brand("apple"),
        price: 74900, mrp: 79900, discount_percent: 6, sku: "APPL-IP15-128-001",
        stock: 100, low_stock_threshold: 15, is_featured: true, is_bestseller: true,
        thumbnail: imgs("phone")[0],
        images: imgs("phone"),
        tags: ["iphone","apple","smartphone","ios"],
        specifications: [{ key:"Processor",value:"A16 Bionic"},{ key:"RAM",value:"6 GB"},{ key:"Storage",value:"128 GB"},{ key:"Camera",value:"48 MP + 12 MP"}],
        weight: 171, rating_avg: 4.8, rating_count: 920, total_sold: 2400, status: true,
      },
      {
        name: "Samsung Galaxy S24 256GB",
        slug: toSlug("Samsung Galaxy S24 256GB"),
        short_description: "Snapdragon 8 Gen 3, 50MP camera, Galaxy AI features",
        description: "Samsung Galaxy S24 brings Galaxy AI to your fingertips with a powerful Snapdragon chip and excellent camera system.",
        category_id: cat("mobiles"), subcategory_id: cat("smartphones"), brand_id: brand("samsung"),
        price: 74999, mrp: 79999, discount_percent: 6, sku: "SAM-S24-256-001",
        stock: 85, low_stock_threshold: 10, is_featured: true,
        thumbnail: imgs("phone")[1],
        images: imgs("phone"),
        tags: ["samsung","galaxy","android","smartphone"],
        specifications: [{ key:"Processor",value:"Snapdragon 8 Gen 3"},{ key:"RAM",value:"8 GB"},{ key:"Storage",value:"256 GB"},{ key:"Camera",value:"50 MP + 10 MP + 12 MP"}],
        weight: 167, rating_avg: 4.7, rating_count: 740, total_sold: 1850, status: true,
      },
      {
        name: "OnePlus 12 256GB",
        slug: toSlug("OnePlus 12 256GB"),
        short_description: "Snapdragon 8 Gen 3, 50MP Hasselblad camera, 100W charging",
        description: "OnePlus 12 delivers flagship performance with ultra-fast 100W SUPERVOOC charging and Hasselblad-tuned cameras.",
        category_id: cat("mobiles"), subcategory_id: cat("smartphones"), brand_id: brand("oneplus"),
        price: 64999, mrp: 69999, discount_percent: 7, sku: "OP-12-256-001",
        stock: 70, low_stock_threshold: 10, is_bestseller: true,
        thumbnail: imgs("phone")[2],
        images: imgs("phone"),
        tags: ["oneplus","android","smartphone","flagship"],
        specifications: [{ key:"Processor",value:"Snapdragon 8 Gen 3"},{ key:"RAM",value:"12 GB"},{ key:"Storage",value:"256 GB"},{ key:"Battery",value:"5400 mAh"}],
        weight: 220, rating_avg: 4.6, rating_count: 580, total_sold: 1400, status: true,
      },
      {
        name: "Xiaomi Redmi Note 13 Pro 128GB",
        slug: toSlug("Xiaomi Redmi Note 13 Pro 128GB"),
        short_description: "Dimensity 7200, 200MP camera, 67W charging, AMOLED display",
        description: "Redmi Note 13 Pro packs a 200MP camera, crisp AMOLED display and fast charging at a great price.",
        category_id: cat("mobiles"), subcategory_id: cat("smartphones"), brand_id: brand("xiaomi"),
        price: 26999, mrp: 31999, discount_percent: 16, sku: "XMI-RN13P-128-001",
        stock: 120, low_stock_threshold: 15, is_new_arrival: true,
        thumbnail: imgs("phone")[3],
        images: imgs("phone"),
        tags: ["xiaomi","redmi","android","smartphone"],
        specifications: [{ key:"Processor",value:"Dimensity 7200 Ultra"},{ key:"RAM",value:"8 GB"},{ key:"Storage",value:"128 GB"},{ key:"Camera",value:"200 MP"}],
        weight: 187, rating_avg: 4.4, rating_count: 490, total_sold: 1650, status: true,
      },
      {
        name: "Realme Narzo 70 Pro 5G 128GB",
        slug: toSlug("Realme Narzo 70 Pro 5G 128GB"),
        short_description: "Dimensity 7050, 50MP Sony IMX890 camera, 67W charging",
        description: "Narzo 70 Pro 5G offers 5G connectivity with a premium Sony camera sensor and fast SuperVOOC charging.",
        category_id: cat("mobiles"), subcategory_id: cat("smartphones"), brand_id: brand("realme"),
        price: 19999, mrp: 24999, discount_percent: 20, sku: "RM-N70P-128-001",
        stock: 95, low_stock_threshold: 12,
        thumbnail: imgs("phone")[0],
        images: imgs("phone"),
        tags: ["realme","5g","android","narzo"],
        specifications: [{ key:"Processor",value:"Dimensity 7050"},{ key:"RAM",value:"8 GB"},{ key:"Storage",value:"128 GB"},{ key:"Display",value:"6.7 inch AMOLED 120Hz"}],
        weight: 181, rating_avg: 4.3, rating_count: 310, total_sold: 870, status: true,
      },
      {
        name: "Motorola Edge 50 Pro 256GB",
        slug: toSlug("Motorola Edge 50 Pro 256GB"),
        short_description: "Snapdragon 7s Gen 2, 50MP camera, 125W TurboPower charging",
        description: "Motorola Edge 50 Pro brings 125W TurboPower charging and a beautiful curved pOLED display.",
        category_id: cat("mobiles"), subcategory_id: cat("smartphones"), brand_id: brand("motorola"),
        price: 29999, mrp: 35999, discount_percent: 17, sku: "MOTO-E50P-256-001",
        stock: 80, low_stock_threshold: 10, is_new_arrival: true,
        thumbnail: imgs("phone")[1],
        images: imgs("phone"),
        tags: ["motorola","android","smartphone","edge"],
        specifications: [{ key:"Processor",value:"Snapdragon 7s Gen 2"},{ key:"RAM",value:"12 GB"},{ key:"Storage",value:"256 GB"},{ key:"Charging",value:"125W TurboPower"}],
        weight: 186, rating_avg: 4.4, rating_count: 240, total_sold: 580, status: true,
      },
      {
        name: "Google Pixel 8 Pro 256GB",
        slug: toSlug("Google Pixel 8 Pro 256GB"),
        short_description: "Google Tensor G3, 50MP camera, 7 years OS updates, AI features",
        description: "Pixel 8 Pro with Google Tensor G3 delivers exceptional AI-powered photography and 7 years of updates.",
        category_id: cat("mobiles"), subcategory_id: cat("smartphones"), brand_id: brand("google"),
        price: 89999, mrp: 99999, discount_percent: 10, sku: "GOOG-P8P-256-001",
        stock: 50, low_stock_threshold: 8, is_featured: true,
        thumbnail: imgs("phone")[2],
        images: imgs("phone"),
        tags: ["google","pixel","android","smartphone","ai"],
        specifications: [{ key:"Processor",value:"Google Tensor G3"},{ key:"RAM",value:"12 GB"},{ key:"Storage",value:"256 GB"},{ key:"Camera",value:"50 MP + 48 MP + 48 MP"}],
        weight: 213, rating_avg: 4.6, rating_count: 380, total_sold: 720, status: true,
      },
      // ── SMARTWATCHES & TABLETS ────────────────────────────────────────────
      {
        name: "Apple Watch Series 9 GPS 45mm",
        slug: toSlug("Apple Watch Series 9 GPS 45mm"),
        short_description: "S9 chip, Double Tap gesture, always-on Retina display",
        description: "Apple Watch Series 9 with S9 chip and Double Tap gesture is the most advanced Apple Watch ever.",
        category_id: cat("mobiles"), subcategory_id: cat("smartwatches"), brand_id: brand("apple"),
        price: 44900, mrp: 48900, discount_percent: 8, sku: "APPL-AWS9-45G-001",
        stock: 45, low_stock_threshold: 8, is_featured: true,
        thumbnail: imgs("smartwatch")[0],
        images: imgs("smartwatch"),
        tags: ["smartwatch","apple","watch","fitness"],
        specifications: [{ key:"Chip",value:"Apple S9"},{ key:"Case Size",value:"45 mm"},{ key:"Display",value:"Always-on Retina LTPO OLED"},{ key:"Water Resistance",value:"50m"}],
        weight: 51, rating_avg: 4.9, rating_count: 420, total_sold: 900, status: true,
      },
      {
        name: "Samsung Galaxy Watch 6 Classic 47mm",
        slug: toSlug("Samsung Galaxy Watch 6 Classic 47mm"),
        short_description: "Rotating bezel, Exynos W930, advanced health tracking",
        description: "Galaxy Watch 6 Classic brings back the iconic rotating bezel with premium health and fitness tracking.",
        category_id: cat("mobiles"), subcategory_id: cat("smartwatches"), brand_id: brand("samsung"),
        price: 34999, mrp: 39999, discount_percent: 13, sku: "SAM-GW6C-47-001",
        stock: 55, low_stock_threshold: 8,
        thumbnail: imgs("smartwatch")[1],
        images: imgs("smartwatch"),
        tags: ["smartwatch","samsung","galaxy-watch","fitness"],
        specifications: [{ key:"Case Size",value:"47 mm"},{ key:"Display",value:"1.47 inch Super AMOLED"},{ key:"Battery",value:"425 mAh"},{ key:"OS",value:"Wear OS 4"}],
        weight: 59, rating_avg: 4.6, rating_count: 310, total_sold: 650, status: true,
      },
      {
        name: "Apple iPad 10th Gen 64GB WiFi",
        slug: toSlug("Apple iPad 10th Gen 64GB WiFi"),
        short_description: "A14 Bionic, 10.9-inch Liquid Retina, 12MP camera",
        description: "iPad 10th gen with A14 Bionic chip delivers powerful performance for work, learning and entertainment.",
        category_id: cat("electronics"), subcategory_id: cat("tablets"), brand_id: brand("apple"),
        price: 44900, mrp: 49900, discount_percent: 10, sku: "APPL-IPAD10-64W-001",
        stock: 60, low_stock_threshold: 8, is_featured: true,
        thumbnail: imgs("tablet")[0],
        images: imgs("tablet"),
        tags: ["ipad","apple","tablet","ios"],
        specifications: [{ key:"Chip",value:"A14 Bionic"},{ key:"Display",value:"10.9-inch Liquid Retina"},{ key:"Storage",value:"64 GB"},{ key:"Camera",value:"12 MP"}],
        weight: 477, rating_avg: 4.8, rating_count: 560, total_sold: 1200, status: true,
      },
      {
        name: "Samsung Galaxy Tab S9 FE 128GB",
        slug: toSlug("Samsung Galaxy Tab S9 FE 128GB"),
        short_description: "Exynos 1380, 10.9-inch WUXGA+, S Pen included, 45W charging",
        description: "Galaxy Tab S9 FE comes with an S Pen for creativity and productivity on a large vivid display.",
        category_id: cat("electronics"), subcategory_id: cat("tablets"), brand_id: brand("samsung"),
        price: 44999, mrp: 52999, discount_percent: 15, sku: "SAM-TABS9FE-128-001",
        stock: 50, low_stock_threshold: 8,
        thumbnail: imgs("tablet")[1],
        images: imgs("tablet"),
        tags: ["tablet","samsung","galaxy","android"],
        specifications: [{ key:"Processor",value:"Exynos 1380"},{ key:"Display",value:"10.9-inch WUXGA+"},{ key:"Storage",value:"128 GB"},{ key:"Stylus",value:"S Pen Included"}],
        weight: 523, rating_avg: 4.5, rating_count: 320, total_sold: 680, status: true,
      },
      // ── CAMERAS ───────────────────────────────────────────────────────────
      {
        name: "Sony Alpha ZV-E10 Mirrorless Camera 16-50mm",
        slug: toSlug("Sony Alpha ZV-E10 Mirrorless Camera 16-50mm"),
        short_description: "24.2MP APS-C sensor, 4K video, vlog-optimised, lightweight",
        description: "Sony ZV-E10 is the perfect mirrorless vlogging camera with a large APS-C sensor, 4K video and interchangeable lenses.",
        category_id: cat("electronics"), subcategory_id: cat("cameras"), brand_id: brand("sony"),
        price: 59990, mrp: 69990, discount_percent: 14, sku: "SONY-ZVE10-1650-001",
        stock: 40, low_stock_threshold: 5, is_new_arrival: true, is_featured: true,
        thumbnail: imgs("camera")[0],
        images: imgs("camera"),
        tags: ["camera","sony","mirrorless","vlog","4k"],
        specifications: [{ key:"Sensor",value:"24.2 MP APS-C CMOS"},{ key:"Video",value:"4K 30fps"},{ key:"Mount",value:"Sony E-mount"},{ key:"Display",value:"3-inch Tiltable LCD"}],
        weight: 343, rating_avg: 4.7, rating_count: 480, total_sold: 960, status: true,
      },
      {
        name: "Canon EOS 1500D DSLR Camera 18-55mm Kit",
        slug: toSlug("Canon EOS 1500D DSLR Camera 18-55mm Kit"),
        short_description: "24.1MP APS-C CMOS, DIGIC 4+, Full HD video, Wi-Fi & NFC",
        description: "Canon EOS 1500D is the perfect beginner DSLR with 24.1MP sensor, easy shooting modes and built-in Wi-Fi.",
        category_id: cat("electronics"), subcategory_id: cat("cameras"), brand_id: brand("sony"),
        price: 29990, mrp: 36990, discount_percent: 19, sku: "CAN-1500D-001",
        stock: 55, low_stock_threshold: 8,
        thumbnail: imgs("camera")[1],
        images: imgs("camera"),
        tags: ["camera","canon","dslr","photography"],
        specifications: [{ key:"Sensor",value:"24.1 MP APS-C CMOS"},{ key:"Processor",value:"DIGIC 4+"},{ key:"Video",value:"Full HD 1080p"},{ key:"Connectivity",value:"Wi-Fi + NFC"}],
        weight: 475, rating_avg: 4.6, rating_count: 640, total_sold: 1100, status: true,
      },
      // ── FASHION ───────────────────────────────────────────────────────────
      {
        name: "Nike Air Max 270 Running Shoes",
        slug: toSlug("Nike Air Max 270 Running Shoes"),
        short_description: "Max Air cushioning, mesh upper, rubber outsole",
        description: "Nike Air Max 270 delivers all-day comfort with the largest Air unit in heel and a lightweight mesh upper.",
        category_id: cat("fashion"), subcategory_id: cat("footwear"), brand_id: brand("nike"),
        price: 9995, mrp: 12995, discount_percent: 23, sku: "NIKE-AM270-001",
        stock: 150, low_stock_threshold: 20, is_featured: true, is_bestseller: true,
        thumbnail: imgs("shoes")[0],
        images: imgs("shoes"),
        tags: ["shoes","nike","running","sports"],
        specifications: [{ key:"Material",value:"Mesh + Synthetic"},{ key:"Sole",value:"Rubber"},{ key:"Closure",value:"Lace-up"},{ key:"Occasion",value:"Sports / Casual"}],
        weight: 340, rating_avg: 4.6, rating_count: 780, total_sold: 2100, status: true,
      },
      {
        name: "Adidas Ultraboost 22 Running Shoes",
        slug: toSlug("Adidas Ultraboost 22 Running Shoes"),
        short_description: "BOOST midsole, Primeknit upper, Continental rubber outsole",
        description: "Ultraboost 22 returns energy with every step thanks to BOOST technology and a foot-hugging Primeknit upper.",
        category_id: cat("fashion"), subcategory_id: cat("footwear"), brand_id: brand("adidas"),
        price: 14999, mrp: 17999, discount_percent: 17, sku: "ADS-UB22-001",
        stock: 90, low_stock_threshold: 15,
        thumbnail: imgs("shoes")[1],
        images: imgs("shoes"),
        tags: ["shoes","adidas","running","boost"],
        specifications: [{ key:"Material",value:"Primeknit"},{ key:"Midsole",value:"BOOST"},{ key:"Outsole",value:"Continental Rubber"}],
        weight: 310, rating_avg: 4.7, rating_count: 630, total_sold: 1450, status: true,
      },
      {
        name: "Levi's 511 Slim Fit Jeans",
        slug: toSlug("Levis 511 Slim Fit Jeans"),
        short_description: "Stretch denim, slim fit, sits below waist, tapered leg",
        description: "Levi's 511 Slim Fit Jeans offer a modern slim silhouette with stretch comfort for all-day wear.",
        category_id: cat("fashion"), subcategory_id: cat("mens-clothing"), brand_id: brand("levis"),
        price: 2999, mrp: 3999, discount_percent: 25, sku: "LEV-511-SLM-001",
        stock: 200, low_stock_threshold: 25, is_bestseller: true,
        thumbnail: imgs("clothing")[0],
        images: imgs("clothing"),
        tags: ["jeans","levis","men","denim"],
        specifications: [{ key:"Fit",value:"Slim"},{ key:"Fabric",value:"99% Cotton, 1% Elastane"},{ key:"Rise",value:"Mid Rise"}],
        weight: 650, rating_avg: 4.5, rating_count: 920, total_sold: 3200, status: true,
      },
      {
        name: "Allen Solly Men's Formal Shirt",
        slug: toSlug("Allen Solly Mens Formal Shirt"),
        short_description: "Regular fit, solid colour, full sleeve formal shirt",
        description: "Allen Solly formal shirt crafted from premium cotton blend offers a sharp, professional look.",
        category_id: cat("fashion"), subcategory_id: cat("mens-clothing"), brand_id: brand("allen-solly"),
        price: 1199, mrp: 1799, discount_percent: 33, sku: "AS-FSH-REG-001",
        stock: 300, low_stock_threshold: 30,
        thumbnail: imgs("clothing")[1],
        images: imgs("clothing"),
        tags: ["shirt","formal","men","allen-solly"],
        specifications: [{ key:"Fabric",value:"Cotton Blend"},{ key:"Fit",value:"Regular"},{ key:"Sleeve",value:"Full Sleeve"},{ key:"Occasion",value:"Formal"}],
        weight: 300, rating_avg: 4.3, rating_count: 540, total_sold: 1800, status: true,
      },
      {
        name: "H&M Women's Floral Midi Dress",
        slug: toSlug("HM Womens Floral Midi Dress"),
        short_description: "V-neck, floral print, midi length, casual dress",
        description: "H&M floral midi dress features a flattering V-neck, flowy fabric and vibrant floral print for casual outings.",
        category_id: cat("fashion"), subcategory_id: cat("womens-clothing"), brand_id: brand("hm"),
        price: 1499, mrp: 2199, discount_percent: 32, sku: "HM-WMD-FL-001",
        stock: 180, low_stock_threshold: 20, is_new_arrival: true,
        thumbnail: img("womens floral midi dress"),
        images: [img("floral dress women"),img("midi dress fashion"),img("summer dress"),img("women casual dress")],
        tags: ["dress","women","floral","hm","casual"],
        specifications: [{ key:"Fabric",value:"Woven"},{ key:"Neckline",value:"V-Neck"},{ key:"Length",value:"Midi"},{ key:"Fit",value:"Regular"}],
        weight: 350, rating_avg: 4.4, rating_count: 370, total_sold: 980, status: true,
      },
      {
        name: "Puma Men's Sports Track Pant",
        slug: toSlug("Puma Mens Sports Track Pant"),
        short_description: "Dry Cell technology, elastic waistband, side pockets",
        description: "Puma track pant with Dry Cell moisture-wicking technology keeps you comfortable during workouts.",
        category_id: cat("fashion"), subcategory_id: cat("mens-clothing"), brand_id: brand("puma"),
        price: 1799, mrp: 2499, discount_percent: 28, sku: "PUM-TRK-M-001",
        stock: 160, low_stock_threshold: 20,
        thumbnail: img("puma track pants sports"),
        images: [img("track pant men"),img("sports trouser"),img("puma sportswear"),img("gym pants")],
        tags: ["trackpant","puma","men","sports"],
        specifications: [{ key:"Fabric",value:"Polyester"},{ key:"Fit",value:"Regular"},{ key:"Technology",value:"Dry Cell"}],
        weight: 280, rating_avg: 4.3, rating_count: 290, total_sold: 750, status: true,
      },
      {
        name: "Van Heusen Men's Chino Trousers",
        slug: toSlug("Van Heusen Mens Chino Trousers"),
        short_description: "Slim fit, stretch cotton, casual chinos",
        description: "Van Heusen slim fit chino trousers in stretch cotton for a smart casual look all day long.",
        category_id: cat("fashion"), subcategory_id: cat("mens-clothing"), brand_id: brand("van-heusen"),
        price: 1699, mrp: 2499, discount_percent: 32, sku: "VH-CHN-SLM-001",
        stock: 180, low_stock_threshold: 20,
        thumbnail: img("men chino trousers"),
        images: [img("chinos pants men"),img("slim trousers"),img("casual pants men"),img("smart casual outfit")],
        tags: ["chinos","trousers","men","van-heusen"],
        specifications: [{ key:"Fabric",value:"98% Cotton, 2% Elastane"},{ key:"Fit",value:"Slim"},{ key:"Occasion",value:"Casual / Smart Casual"}],
        weight: 450, rating_avg: 4.3, rating_count: 320, total_sold: 880, status: true,
      },
      {
        name: "Bata Men's Formal Leather Shoes",
        slug: toSlug("Bata Mens Formal Leather Shoes"),
        short_description: "Genuine leather upper, cushioned footbed, slip-on",
        description: "Bata formal leather shoes with a cushioned insole and genuine leather upper for all-day comfort.",
        category_id: cat("fashion"), subcategory_id: cat("footwear"), brand_id: brand("bata"),
        price: 2499, mrp: 3499, discount_percent: 29, sku: "BATA-FLS-M-001",
        stock: 140, low_stock_threshold: 15,
        thumbnail: img("bata formal leather shoes"),
        images: [img("formal leather shoes"),img("oxford shoes"),img("men dress shoes"),img("leather footwear")],
        tags: ["shoes","formal","bata","leather","men"],
        specifications: [{ key:"Material",value:"Genuine Leather"},{ key:"Sole",value:"TPR"},{ key:"Closure",value:"Slip-on"},{ key:"Occasion",value:"Formal"}],
        weight: 800, rating_avg: 4.4, rating_count: 480, total_sold: 1200, status: true,
      },
      // ── HOME & KITCHEN ────────────────────────────────────────────────────
      {
        name: "Prestige Omega Deluxe Granite Fry Pan 24cm",
        slug: toSlug("Prestige Omega Deluxe Granite Fry Pan 24cm"),
        short_description: "Non-stick granite coating, induction compatible, bakelite handle",
        description: "Prestige Omega Deluxe fry pan with superior granite non-stick coating for healthy, oil-free cooking.",
        category_id: cat("home-kitchen"), subcategory_id: cat("cookware"), brand_id: brand("prestige"),
        price: 899, mrp: 1299, discount_percent: 31, sku: "PRE-FP-GR-24-001",
        stock: 250, low_stock_threshold: 30, is_bestseller: true,
        thumbnail: img("non stick fry pan cookware"),
        images: [img("granite fry pan"),img("non stick pan"),img("cookware kitchen"),img("frying pan cooking")],
        tags: ["frypan","non-stick","prestige","cookware"],
        specifications: [{ key:"Material",value:"Aluminium with Granite Coating"},{ key:"Diameter",value:"24 cm"},{ key:"Compatible",value:"Induction + Gas"}],
        weight: 780, rating_avg: 4.4, rating_count: 850, total_sold: 2600, status: true,
      },
      {
        name: "Milton Thermosteel Flip Lid Bottle 1L",
        slug: toSlug("Milton Thermosteel Flip Lid Bottle 1L"),
        short_description: "Double wall stainless steel, 24hr hot/cold retention",
        description: "Milton Thermosteel keeps beverages hot for 24 hours and cold for 24 hours with double wall insulation.",
        category_id: cat("home-kitchen"), subcategory_id: cat("cookware"), brand_id: brand("milton"),
        price: 699, mrp: 999, discount_percent: 30, sku: "MLT-TSB-1L-001",
        stock: 400, low_stock_threshold: 40, is_bestseller: true,
        thumbnail: img("thermos bottle stainless steel"),
        images: [img("insulated water bottle"),img("milton bottle"),img("steel bottle"),img("flip lid bottle")],
        tags: ["bottle","milton","thermosteel","insulated"],
        specifications: [{ key:"Capacity",value:"1 Litre"},{ key:"Material",value:"Stainless Steel"},{ key:"Hot retention",value:"24 hours"}],
        weight: 400, rating_avg: 4.5, rating_count: 1200, total_sold: 4500, status: true,
      },
      {
        name: "IKEA KALLAX Shelf Unit White",
        slug: toSlug("IKEA KALLAX Shelf Unit White"),
        short_description: "4-cube storage shelf, 77x77cm, fits boxes and baskets",
        description: "IKEA KALLAX is a versatile shelf unit that can be used as a room divider, shelving or storage unit.",
        category_id: cat("home-kitchen"), subcategory_id: cat("storage"), brand_id: brand("ikea"),
        price: 5999, mrp: 7499, discount_percent: 20, sku: "IKEA-KLX-4C-001",
        stock: 60, low_stock_threshold: 8,
        thumbnail: img("ikea kallax shelf unit"),
        images: [img("shelf unit storage"),img("cube bookshelf"),img("white shelf"),img("storage furniture")],
        tags: ["shelf","storage","ikea","furniture"],
        specifications: [{ key:"Dimensions",value:"77 x 77 cm"},{ key:"Material",value:"Particleboard"},{ key:"Colour",value:"White"},{ key:"Compartments",value:"4"}],
        weight: 25000, rating_avg: 4.6, rating_count: 440, total_sold: 1100, status: true,
      },
      {
        name: "Pigeon Stainless Steel Pressure Cooker 5L",
        slug: toSlug("Pigeon Stainless Steel Pressure Cooker 5L"),
        short_description: "5 Litre, induction base, ISI certified, safety valve",
        description: "Pigeon stainless steel pressure cooker with induction-friendly base cooks food faster and retains nutrients.",
        category_id: cat("home-kitchen"), subcategory_id: cat("cookware"), brand_id: brand("pigeon"),
        price: 1199, mrp: 1799, discount_percent: 33, sku: "PIG-PC-5L-SS-001",
        stock: 300, low_stock_threshold: 30,
        thumbnail: img("pressure cooker stainless steel"),
        images: [img("steel pressure cooker"),img("pigeon cooker"),img("induction cooker"),img("kitchen pressure cooker")],
        tags: ["pressure-cooker","pigeon","cookware","kitchen"],
        specifications: [{ key:"Capacity",value:"5 Litres"},{ key:"Material",value:"Stainless Steel"},{ key:"Compatible",value:"Induction + Gas"},{ key:"Certification",value:"ISI"}],
        weight: 1800, rating_avg: 4.4, rating_count: 760, total_sold: 2200, status: true,
      },
      // ── APPLIANCES ────────────────────────────────────────────────────────
      {
        name: "Samsung 8Kg Front Load Washing Machine",
        slug: toSlug("Samsung 8Kg Front Load Washing Machine"),
        short_description: "Eco Bubble technology, 1400 RPM, Digital Inverter Motor",
        description: "Samsung front load washing machine with Eco Bubble technology generates bubbles for a thorough clean.",
        category_id: cat("appliances"), subcategory_id: cat("washing-machines"), brand_id: brand("samsung"),
        price: 39990, mrp: 49990, discount_percent: 20, sku: "SAM-WM-8KG-FL-001",
        stock: 35, low_stock_threshold: 5, is_featured: true,
        thumbnail: img("samsung front load washing machine"),
        images: [img("washing machine front load"),img("samsung washer"),img("front loader"),img("home appliance laundry")],
        tags: ["washing-machine","samsung","front-load","appliances"],
        specifications: [{ key:"Capacity",value:"8 Kg"},{ key:"Type",value:"Front Load"},{ key:"RPM",value:"1400"},{ key:"Energy Rating",value:"5 Star"}],
        weight: 72000, rating_avg: 4.5, rating_count: 380, total_sold: 720, status: true,
      },
      {
        name: "LG 260L Double Door Refrigerator",
        slug: toSlug("LG 260L Double Door Refrigerator"),
        short_description: "Smart Inverter Compressor, Multi Air Flow, Door Cooling+",
        description: "LG double door refrigerator with Smart Inverter compressor ensures energy efficiency and uniform cooling.",
        category_id: cat("appliances"), subcategory_id: cat("refrigerators"), brand_id: brand("lg"),
        price: 27990, mrp: 35990, discount_percent: 22, sku: "LG-REF-260L-DD-001",
        stock: 40, low_stock_threshold: 5,
        thumbnail: img("lg double door refrigerator"),
        images: [img("refrigerator double door"),img("fridge kitchen"),img("lg refrigerator"),img("home fridge appliance")],
        tags: ["refrigerator","lg","double-door","appliances"],
        specifications: [{ key:"Capacity",value:"260 Litres"},{ key:"Type",value:"Double Door"},{ key:"Energy Rating",value:"2 Star"},{ key:"Compressor",value:"Smart Inverter"}],
        weight: 57000, rating_avg: 4.4, rating_count: 320, total_sold: 680, status: true,
      },
      {
        name: "Voltas 1.5 Ton 3 Star Split AC",
        slug: toSlug("Voltas 1.5 Ton 3 Star Split AC"),
        short_description: "Adjustable cooling, auto-clean, 4-in-1 convertible",
        description: "Voltas split AC with 4-in-1 convertible mode adapts cooling as per requirement saving energy.",
        category_id: cat("appliances"), subcategory_id: cat("air-conditioners"), brand_id: brand("lg"),
        price: 34990, mrp: 42990, discount_percent: 19, sku: "VOLT-AC-15T-3S-001",
        stock: 30, low_stock_threshold: 5,
        thumbnail: img("split air conditioner"),
        images: [img("ac indoor unit"),img("split ac wall"),img("air conditioner room"),img("ac appliance")],
        tags: ["ac","split","air-conditioner","appliances"],
        specifications: [{ key:"Capacity",value:"1.5 Ton"},{ key:"Star Rating",value:"3 Star"},{ key:"Type",value:"Split"},{ key:"Inverter",value:"Yes"}],
        weight: 35000, rating_avg: 4.3, rating_count: 270, total_sold: 540, status: true,
      },
      {
        name: "Philips HD Mixer Grinder 750W",
        slug: toSlug("Philips HD Mixer Grinder 750W"),
        short_description: "750W motor, 3 jars, ProBlend 5 technology",
        description: "Philips mixer grinder with ProBlend 5 star technology for superior blending and grinding performance.",
        category_id: cat("appliances"), subcategory_id: cat("microwaves"), brand_id: brand("philips"),
        price: 3499, mrp: 4999, discount_percent: 30, sku: "PHIL-MG-750W-001",
        stock: 200, low_stock_threshold: 25, is_bestseller: true,
        thumbnail: img("philips mixer grinder"),
        images: [img("mixer grinder kitchen"),img("blender grinder"),img("philips appliance"),img("kitchen mixer")],
        tags: ["mixer","grinder","philips","kitchen"],
        specifications: [{ key:"Power",value:"750 Watts"},{ key:"Jars",value:"3"},{ key:"Speed",value:"3 + Pulse"}],
        weight: 3500, rating_avg: 4.5, rating_count: 1100, total_sold: 3200, status: true,
      },
      {
        name: "Bajaj Majesty 1000W Sandwich Maker",
        slug: toSlug("Bajaj Majesty 1000W Sandwich Maker"),
        short_description: "Non-stick plates, pilot lamp, 1000W, cool touch handle",
        description: "Bajaj Majesty sandwich maker with non-stick plates ensures perfectly toasted sandwiches every time.",
        category_id: cat("appliances"), subcategory_id: cat("microwaves"), brand_id: brand("bajaj"),
        price: 849, mrp: 1299, discount_percent: 35, sku: "BAJ-SM-1000W-001",
        stock: 300, low_stock_threshold: 30,
        thumbnail: img("sandwich maker toaster"),
        images: [img("sandwich toaster grill"),img("electric sandwich maker"),img("breakfast maker"),img("toaster kitchen")],
        tags: ["sandwich-maker","bajaj","kitchen","appliances"],
        specifications: [{ key:"Power",value:"1000 Watts"},{ key:"Plates",value:"Non-stick"},{ key:"Indicator",value:"Pilot Lamp"}],
        weight: 1200, rating_avg: 4.3, rating_count: 780, total_sold: 2200, status: true,
      },
      {
        name: "Whirlpool 7.5Kg Top Load Washing Machine",
        slug: toSlug("Whirlpool 7.5Kg Top Load Washing Machine"),
        short_description: "ZPF Technology, 5-star energy, 12 wash programs",
        description: "Whirlpool top load washing machine with Zero Pressure Fill technology works even with low water pressure.",
        category_id: cat("appliances"), subcategory_id: cat("washing-machines"), brand_id: brand("whirlpool"),
        price: 22990, mrp: 29990, discount_percent: 23, sku: "WP-WM-75KG-TL-001",
        stock: 45, low_stock_threshold: 5,
        thumbnail: img("top load washing machine"),
        images: [img("whirlpool washing machine"),img("top loader washer"),img("washing machine"),img("laundry appliance")],
        tags: ["washing-machine","whirlpool","top-load","appliances"],
        specifications: [{ key:"Capacity",value:"7.5 Kg"},{ key:"Type",value:"Top Load"},{ key:"Energy Rating",value:"5 Star"},{ key:"Programs",value:"12"}],
        weight: 38000, rating_avg: 4.4, rating_count: 420, total_sold: 860, status: true,
      },
      // ── BOOKS ─────────────────────────────────────────────────────────────
      {
        name: "Atomic Habits by James Clear",
        slug: toSlug("Atomic Habits by James Clear"),
        short_description: "Build good habits, break bad ones - #1 NYT Bestseller",
        description: "Atomic Habits offers a proven framework for improving every day. James Clear reveals how tiny changes lead to remarkable results.",
        category_id: cat("books"), subcategory_id: cat("non-fiction"), brand_id: brand("penguin"),
        price: 399, mrp: 599, discount_percent: 33, sku: "BK-AH-JC-001",
        stock: 500, low_stock_threshold: 50, is_bestseller: true,
        thumbnail: img("atomic habits book"),
        images: [img("self help book"),img("book reading"),img("atomic habits"),img("bestseller book")],
        tags: ["book","self-help","habits","james-clear"],
        specifications: [{ key:"Author",value:"James Clear"},{ key:"Pages",value:"320"},{ key:"Language",value:"English"},{ key:"Format",value:"Paperback"}],
        weight: 300, rating_avg: 4.9, rating_count: 2400, total_sold: 8000, status: true,
      },
      {
        name: "Rich Dad Poor Dad by Robert Kiyosaki",
        slug: toSlug("Rich Dad Poor Dad by Robert Kiyosaki"),
        short_description: "What the rich teach their kids about money - Bestseller",
        description: "Rich Dad Poor Dad is a classic personal finance book that challenges conventional thinking about money and investing.",
        category_id: cat("books"), subcategory_id: cat("non-fiction"), brand_id: brand("harper-collins"),
        price: 299, mrp: 450, discount_percent: 34, sku: "BK-RDPD-RK-001",
        stock: 600, low_stock_threshold: 50, is_bestseller: true,
        thumbnail: img("rich dad poor dad book finance"),
        images: [img("personal finance book"),img("money book"),img("rich dad"),img("financial book")],
        tags: ["book","finance","money","kiyosaki"],
        specifications: [{ key:"Author",value:"Robert T. Kiyosaki"},{ key:"Pages",value:"336"},{ key:"Language",value:"English"},{ key:"Format",value:"Paperback"}],
        weight: 280, rating_avg: 4.7, rating_count: 3100, total_sold: 10000, status: true,
      },
      {
        name: "The Alchemist by Paulo Coelho",
        slug: toSlug("The Alchemist by Paulo Coelho"),
        short_description: "A magical story about following your dreams",
        description: "The Alchemist is a timeless tale of self-discovery and pursuing one's Personal Legend.",
        category_id: cat("books"), subcategory_id: cat("fiction"), brand_id: brand("harper-collins"),
        price: 249, mrp: 399, discount_percent: 38, sku: "BK-ALK-PC-001",
        stock: 700, low_stock_threshold: 50, is_featured: true,
        thumbnail: img("the alchemist paulo coelho book"),
        images: [img("fiction novel"),img("alchemist book"),img("adventure book"),img("novel paperback")],
        tags: ["book","fiction","coelho","classic"],
        specifications: [{ key:"Author",value:"Paulo Coelho"},{ key:"Pages",value:"197"},{ key:"Language",value:"English"},{ key:"Format",value:"Paperback"}],
        weight: 220, rating_avg: 4.8, rating_count: 4200, total_sold: 14000, status: true,
      },
      {
        name: "Zero to One by Peter Thiel",
        slug: toSlug("Zero to One by Peter Thiel"),
        short_description: "Notes on startups, or how to build the future",
        description: "Zero to One offers fresh perspectives on startups, monopolies, and creating a future that is fundamentally different from today.",
        category_id: cat("books"), subcategory_id: cat("non-fiction"), brand_id: brand("penguin"),
        price: 349, mrp: 499, discount_percent: 30, sku: "BK-Z2O-PT-001",
        stock: 400, low_stock_threshold: 40,
        thumbnail: img("zero to one startup book"),
        images: [img("startup book"),img("business book"),img("entrepreneur book"),img("tech startup")],
        tags: ["book","startup","business","peter-thiel"],
        specifications: [{ key:"Author",value:"Peter Thiel"},{ key:"Pages",value:"224"},{ key:"Language",value:"English"},{ key:"Format",value:"Paperback"}],
        weight: 260, rating_avg: 4.6, rating_count: 1600, total_sold: 5000, status: true,
      },
      // ── SPORTS & FITNESS ──────────────────────────────────────────────────
      {
        name: "Decathlon Domyos 10kg Dumbbell Pair",
        slug: toSlug("Decathlon Domyos 10kg Dumbbell Pair"),
        short_description: "Cast iron, hexagonal shape, non-rolling, pair of 10kg",
        description: "Decathlon Domyos hexagonal dumbbells are ideal for home workouts, featuring non-roll design and comfortable grip.",
        category_id: cat("sports-fitness"), subcategory_id: cat("gym-equipment"), brand_id: brand("decathlon"),
        price: 1599, mrp: 2199, discount_percent: 27, sku: "DEC-DB-10KG-001",
        stock: 200, low_stock_threshold: 20, is_bestseller: true,
        thumbnail: img("dumbbell pair gym"),
        images: [img("dumbbell weights"),img("hexagonal dumbbell"),img("gym equipment"),img("fitness weights")],
        tags: ["dumbbell","gym","fitness","decathlon"],
        specifications: [{ key:"Weight",value:"10 kg each"},{ key:"Material",value:"Cast Iron"},{ key:"Shape",value:"Hexagonal"},{ key:"Grip",value:"Rubber Coated"}],
        weight: 20000, rating_avg: 4.6, rating_count: 560, total_sold: 1400, status: true,
      },
      {
        name: "Cosco Striker Cricket Bat",
        slug: toSlug("Cosco Striker Cricket Bat"),
        short_description: "English willow, full size, with grip and bag cover",
        description: "Cosco Striker cricket bat made from premium English willow with a thick edge for powerful shots.",
        category_id: cat("sports-fitness"), subcategory_id: cat("cricket"), brand_id: brand("cosco"),
        price: 1299, mrp: 1799, discount_percent: 28, sku: "CSC-BAT-STR-001",
        stock: 180, low_stock_threshold: 20,
        thumbnail: img("cricket bat willow"),
        images: [img("cricket bat"),img("english willow bat"),img("cricket gear"),img("cricket sport")],
        tags: ["cricket","bat","cosco","sports"],
        specifications: [{ key:"Wood",value:"English Willow"},{ key:"Size",value:"Full (6)"},{ key:"Handle",value:"Cane Handle"}],
        weight: 1100, rating_avg: 4.3, rating_count: 430, total_sold: 1050, status: true,
      },
      {
        name: "Nivia Yoga Mat 6mm Anti-slip",
        slug: toSlug("Nivia Yoga Mat 6mm Anti-slip"),
        short_description: "6mm thick TPE mat, anti-slip surface, carry strap included",
        description: "Nivia yoga mat with 6mm cushioning and anti-slip texture provides grip and comfort for all yoga styles.",
        category_id: cat("sports-fitness"), subcategory_id: cat("yoga-meditation"), brand_id: brand("nivia"),
        price: 699, mrp: 999, discount_percent: 30, sku: "NIV-YM-6MM-001",
        stock: 300, low_stock_threshold: 30,
        thumbnail: img("yoga mat exercise"),
        images: [img("yoga mat"),img("exercise mat"),img("fitness yoga"),img("purple yoga mat")],
        tags: ["yoga","mat","nivia","fitness"],
        specifications: [{ key:"Thickness",value:"6 mm"},{ key:"Material",value:"TPE"},{ key:"Dimensions",value:"183 x 61 cm"},{ key:"Anti-slip",value:"Yes"}],
        weight: 1000, rating_avg: 4.4, rating_count: 620, total_sold: 1800, status: true,
      },
      {
        name: "Yonex Voltric Badminton Racket",
        slug: toSlug("Yonex Voltric Badminton Racket"),
        short_description: "Carbon graphite, tri-voltage system, unstrung, 85g",
        description: "Yonex Voltric racket combines power and speed with Tri-Voltage System for smashing performance.",
        category_id: cat("sports-fitness"), subcategory_id: cat("gym-equipment"), brand_id: brand("yonex"),
        price: 2499, mrp: 3499, discount_percent: 29, sku: "YON-VT-RAC-001",
        stock: 120, low_stock_threshold: 15,
        thumbnail: img("yonex badminton racket"),
        images: [img("badminton racket"),img("yonex racquet"),img("badminton sport"),img("sports racket")],
        tags: ["badminton","racket","yonex","sports"],
        specifications: [{ key:"Material",value:"Carbon Graphite"},{ key:"Weight",value:"85g"},{ key:"Balance",value:"Head Heavy"},{ key:"Flex",value:"Stiff"}],
        weight: 85, rating_avg: 4.5, rating_count: 340, total_sold: 780, status: true,
      },
      {
        name: "Decathlon 20kg Adjustable Barbell Set",
        slug: toSlug("Decathlon 20kg Adjustable Barbell Set"),
        short_description: "20kg cast iron plates, chrome bar, collars included",
        description: "Complete barbell set for home gym with 20kg cast iron weight plates, chrome steel bar and safety collars.",
        category_id: cat("sports-fitness"), subcategory_id: cat("gym-equipment"), brand_id: brand("decathlon"),
        price: 3499, mrp: 4999, discount_percent: 30, sku: "DEC-BAR-20KG-001",
        stock: 100, low_stock_threshold: 10,
        thumbnail: img("barbell weight set gym"),
        images: [img("barbell plates"),img("home gym barbell"),img("weight lifting bar"),img("gym bar plates")],
        tags: ["barbell","gym","fitness","weights","decathlon"],
        specifications: [{ key:"Total Weight",value:"20 kg"},{ key:"Bar Material",value:"Chrome Steel"},{ key:"Plate Material",value:"Cast Iron"},{ key:"Bar Length",value:"168 cm"}],
        weight: 20000, rating_avg: 4.5, rating_count: 280, total_sold: 620, status: true,
      },
      // ── BEAUTY & PERSONAL CARE ────────────────────────────────────────────
      {
        name: "Lakme Absolute Skin Natural Mousse Foundation",
        slug: toSlug("Lakme Absolute Skin Natural Mousse Foundation"),
        short_description: "SPF8, matte finish, 25g, natural skin tone",
        description: "Lakme Absolute Mousse Foundation gives skin-like finish with SPF8 protection and 16-hour wear.",
        category_id: cat("beauty-personal"), subcategory_id: cat("makeup"), brand_id: brand("lakme"),
        price: 549, mrp: 699, discount_percent: 21, sku: "LAK-FND-MUS-001",
        stock: 250, low_stock_threshold: 25, is_featured: true,
        thumbnail: img("foundation makeup cosmetics"),
        images: [img("lakme foundation"),img("makeup foundation"),img("beauty cosmetics"),img("face makeup")],
        tags: ["foundation","lakme","makeup","beauty"],
        specifications: [{ key:"Finish",value:"Matte"},{ key:"SPF",value:"8"},{ key:"Weight",value:"25g"},{ key:"Type",value:"Mousse"}],
        weight: 100, rating_avg: 4.3, rating_count: 840, total_sold: 2400, status: true,
      },
      {
        name: "L'Oreal Paris Hyaluron Expert Serum 30ml",
        slug: toSlug("LOreal Paris Hyaluron Expert Serum 30ml"),
        short_description: "1.5% pure hyaluronic acid, plumping, hydrating serum",
        description: "L'Oreal Hyaluron Expert Serum with 1.5% Hyaluronic Acid provides intense hydration and visible plumping.",
        category_id: cat("beauty-personal"), subcategory_id: cat("skincare"), brand_id: brand("loreal"),
        price: 799, mrp: 999, discount_percent: 20, sku: "LOR-SRM-HYA-001",
        stock: 200, low_stock_threshold: 20,
        thumbnail: img("hyaluronic acid serum skincare"),
        images: [img("loreal serum"),img("face serum bottle"),img("skincare serum"),img("hydrating skincare")],
        tags: ["serum","loreal","skincare","hyaluronic"],
        specifications: [{ key:"Volume",value:"30 ml"},{ key:"Key Ingredient",value:"Hyaluronic Acid 1.5%"},{ key:"Skin Type",value:"All Skin Types"}],
        weight: 120, rating_avg: 4.5, rating_count: 620, total_sold: 1800, status: true,
      },
      {
        name: "Himalaya Purifying Neem Face Wash 200ml",
        slug: toSlug("Himalaya Purifying Neem Face Wash 200ml"),
        short_description: "Neem & turmeric, removes blackheads, controls oil",
        description: "Himalaya Neem face wash uses natural neem and turmeric to purify skin and control excess oil.",
        category_id: cat("beauty-personal"), subcategory_id: cat("skincare"), brand_id: brand("himalaya"),
        price: 175, mrp: 220, discount_percent: 20, sku: "HIM-FW-NM-200-001",
        stock: 600, low_stock_threshold: 50, is_bestseller: true,
        thumbnail: img("neem face wash cleanser"),
        images: [img("himalaya face wash"),img("face wash tube"),img("skincare cleanser"),img("face wash green")],
        tags: ["face-wash","himalaya","neem","skincare"],
        specifications: [{ key:"Volume",value:"200 ml"},{ key:"Key Ingredient",value:"Neem, Turmeric"},{ key:"Skin Type",value:"Oily / Combination"}],
        weight: 250, rating_avg: 4.4, rating_count: 3200, total_sold: 12000, status: true,
      },
      {
        name: "Mamaearth Onion Hair Fall Control Shampoo 250ml",
        slug: toSlug("Mamaearth Onion Hair Fall Control Shampoo 250ml"),
        short_description: "Onion + plant keratin, reduces breakage, sulphate-free",
        description: "Mamaearth Onion Shampoo with plant keratin strengthens hair from roots and reduces hair fall.",
        category_id: cat("beauty-personal"), subcategory_id: cat("haircare"), brand_id: brand("mamaearth"),
        price: 299, mrp: 399, discount_percent: 25, sku: "MAM-SHP-ONI-250-001",
        stock: 400, low_stock_threshold: 40,
        thumbnail: img("onion shampoo haircare"),
        images: [img("mamaearth shampoo"),img("hair fall shampoo"),img("haircare bottle"),img("natural shampoo")],
        tags: ["shampoo","mamaearth","haircare","onion"],
        specifications: [{ key:"Volume",value:"250 ml"},{ key:"Key Ingredient",value:"Onion Oil, Keratin"},{ key:"Sulphate-free",value:"Yes"}],
        weight: 300, rating_avg: 4.3, rating_count: 1800, total_sold: 6000, status: true,
      },
      {
        name: "Dove Deeply Nourishing Body Lotion 400ml",
        slug: toSlug("Dove Deeply Nourishing Body Lotion 400ml"),
        short_description: "24hr moisture, light texture, NutriumMoisture technology",
        description: "Dove body lotion with NutriumMoisture technology provides 24-hour nourishment for soft, smooth skin.",
        category_id: cat("beauty-personal"), subcategory_id: cat("skincare"), brand_id: brand("dove"),
        price: 349, mrp: 449, discount_percent: 22, sku: "DOV-BL-400-001",
        stock: 350, low_stock_threshold: 35,
        thumbnail: img("body lotion moisturizer"),
        images: [img("dove lotion"),img("body moisturizer"),img("skin care lotion"),img("lotion bottle")],
        tags: ["lotion","dove","skincare","body-care"],
        specifications: [{ key:"Volume",value:"400 ml"},{ key:"Skin Type",value:"Normal to Dry"},{ key:"Technology",value:"NutriumMoisture"}],
        weight: 480, rating_avg: 4.5, rating_count: 1400, total_sold: 4200, status: true,
      },
      {
        name: "Nivea Men Dark Spot Reduction Face Wash 100ml",
        slug: toSlug("Nivea Men Dark Spot Reduction Face Wash 100ml"),
        short_description: "Fights dark spots, 10x Vitamin C, oil-free formula",
        description: "Nivea Men face wash with 10x Vitamin C fights dark spots and uneven skin tone for clear skin.",
        category_id: cat("beauty-personal"), subcategory_id: cat("skincare"), brand_id: brand("nivea"),
        price: 189, mrp: 250, discount_percent: 24, sku: "NIV-MFW-DS-100-001",
        stock: 500, low_stock_threshold: 50,
        thumbnail: img("mens face wash skincare"),
        images: [img("nivea men face wash"),img("men skincare"),img("face wash bottle"),img("vitamin c skincare")],
        tags: ["face-wash","nivea","men","skincare"],
        specifications: [{ key:"Volume",value:"100 ml"},{ key:"Skin Type",value:"Normal to Oily"},{ key:"Key Ingredient",value:"Vitamin C"}],
        weight: 130, rating_avg: 4.3, rating_count: 920, total_sold: 3400, status: true,
      },
      // ── GROCERY ───────────────────────────────────────────────────────────
      {
        name: "Tata Salt Lite Low Sodium 1kg",
        slug: toSlug("Tata Salt Lite Low Sodium 1kg"),
        short_description: "15% less sodium, iodised, vacuum evaporated salt",
        description: "Tata Salt Lite with 15% lower sodium helps maintain heart health without compromising on taste.",
        category_id: cat("grocery"), subcategory_id: cat("dairy-eggs"), brand_id: brand("himalaya"),
        price: 35, mrp: 40, discount_percent: 12, sku: "GRC-SAL-TATA-1K-001",
        stock: 1000, low_stock_threshold: 100,
        thumbnail: img("salt packet grocery"),
        images: [img("kitchen salt"),img("grocery food"),img("salt packet"),img("daily essentials")],
        tags: ["salt","grocery","daily-essentials"],
        specifications: [{ key:"Weight",value:"1 kg"},{ key:"Type",value:"Low Sodium"},{ key:"Iodised",value:"Yes"}],
        weight: 1050, rating_avg: 4.5, rating_count: 900, total_sold: 5000, status: true,
      },
      {
        name: "Haldiram's Aloo Bhujia 400g",
        slug: toSlug("Haldirams Aloo Bhujia 400g"),
        short_description: "Crispy potato snack, traditional recipe, resealable pack",
        description: "Haldiram's Aloo Bhujia is a classic Indian snack made from potatoes and spices following a traditional recipe.",
        category_id: cat("grocery"), subcategory_id: cat("snacks"), brand_id: brand("himalaya"),
        price: 110, mrp: 130, discount_percent: 15, sku: "GRC-SNK-HLDR-400-001",
        stock: 800, low_stock_threshold: 80, is_bestseller: true,
        thumbnail: img("indian snack bhujia"),
        images: [img("haldirams snack"),img("namkeen snack"),img("indian chips"),img("snack packet")],
        tags: ["snacks","bhujia","haldirams","grocery"],
        specifications: [{ key:"Weight",value:"400g"},{ key:"Flavour",value:"Salted"},{ key:"Shelf Life",value:"6 months"}],
        weight: 420, rating_avg: 4.6, rating_count: 1600, total_sold: 7000, status: true,
      },
      {
        name: "Amul Taaza Full Cream Milk 1L",
        slug: toSlug("Amul Taaza Full Cream Milk 1L"),
        short_description: "Full cream standardised milk, 6% fat, fresh & natural",
        description: "Amul Taaza is India's favourite full cream milk with 6% fat, rich in protein and calcium.",
        category_id: cat("grocery"), subcategory_id: cat("dairy-eggs"), brand_id: brand("himalaya"),
        price: 68, mrp: 70, discount_percent: 3, sku: "GRC-MLK-AMUL-1L-001",
        stock: 2000, low_stock_threshold: 200, is_bestseller: true,
        thumbnail: img("milk packet dairy"),
        images: [img("amul milk"),img("full cream milk"),img("dairy milk"),img("milk carton")],
        tags: ["milk","dairy","amul","grocery"],
        specifications: [{ key:"Volume",value:"1 Litre"},{ key:"Type",value:"Full Cream"},{ key:"Fat",value:"6%"},{ key:"Protein",value:"3.5g per 100ml"}],
        weight: 1050, rating_avg: 4.7, rating_count: 2200, total_sold: 15000, status: true,
      },

      // ── TOYS & BABY ───────────────────────────────────────────────────────
      {
        name: "LEGO Classic Creative Brick Box 484 Pieces",
        slug: toSlug("LEGO Classic Creative Brick Box 484 Pieces"),
        short_description: "484 LEGO bricks, multiple colours, ages 4+",
        description: "LEGO Classic Creative Brick Box lets kids build cars, houses, animals and more with 484 colourful bricks.",
        category_id: cat("toys-baby"), subcategory_id: cat("educational-toys"), brand_id: brand("lego"),
        price: 2499, mrp: 3299, discount_percent: 24, sku: "LGO-CLS-484-001",
        stock: 150, low_stock_threshold: 15, is_featured: true,
        thumbnail: img("lego classic bricks toy"),
        images: [img("lego blocks"),img("colorful bricks"),img("lego toys"),img("building blocks kids")],
        tags: ["lego","toys","kids","building-blocks"],
        specifications: [{ key:"Pieces",value:"484"},{ key:"Age",value:"4+"},{ key:"Theme",value:"Classic"}],
        weight: 900, rating_avg: 4.8, rating_count: 720, total_sold: 1900, status: true,
      },
      {
        name: "Hasbro Monopoly Classic Board Game",
        slug: toSlug("Hasbro Monopoly Classic Board Game"),
        short_description: "Classic property trading board game, 2-8 players",
        description: "The classic Monopoly board game for the whole family. Buy, sell, trade properties and build your empire.",
        category_id: cat("toys-baby"), subcategory_id: cat("board-games"), brand_id: brand("hasbro"),
        price: 999, mrp: 1499, discount_percent: 33, sku: "HAS-MNP-CLS-001",
        stock: 200, low_stock_threshold: 20, is_bestseller: true,
        thumbnail: img("monopoly board game"),
        images: [img("board game family"),img("monopoly game"),img("hasbro game"),img("family board game")],
        tags: ["board-game","monopoly","hasbro","family"],
        specifications: [{ key:"Players",value:"2-8"},{ key:"Age",value:"8+"},{ key:"Duration",value:"60-180 min"}],
        weight: 1500, rating_avg: 4.6, rating_count: 950, total_sold: 2800, status: true,
      },
      {
        name: "Fisher-Price Laugh & Learn Smart Stages Chair",
        slug: toSlug("Fisher-Price Laugh Learn Smart Stages Chair"),
        short_description: "3 learning levels, lights & music, age 9-36 months",
        description: "Smart Stages Chair adapts to your baby's growing learning needs with 3 levels of content.",
        category_id: cat("toys-baby"), subcategory_id: cat("educational-toys"), brand_id: brand("fisher-price"),
        price: 1999, mrp: 2799, discount_percent: 29, sku: "FP-LLC-SSC-001",
        stock: 100, low_stock_threshold: 10,
        thumbnail: img("baby learning toy chair"),
        images: [img("fisher price toy"),img("baby toy educational"),img("infant toy"),img("baby activity toy")],
        tags: ["baby","toy","educational","fisher-price"],
        specifications: [{ key:"Age",value:"9-36 months"},{ key:"Levels",value:"3"},{ key:"Features",value:"Lights, Music, Phrases"}],
        weight: 1600, rating_avg: 4.7, rating_count: 480, total_sold: 1100, status: true,
      },
      // ── AUTOMOTIVE ────────────────────────────────────────────────────────
      {
        name: "3M Auto Specialty Microfibre Cloth 40x40cm",
        slug: toSlug("3M Auto Specialty Microfibre Cloth 40x40cm"),
        short_description: "Ultra-soft 380 GSM, lint-free, streak-free finish",
        description: "3M Auto microfibre cloth with 380 GSM provides professional-grade cleaning without scratching surfaces.",
        category_id: cat("automotive"), subcategory_id: cat("car-accessories"), brand_id: brand("3m"),
        price: 249, mrp: 349, discount_percent: 29, sku: "3M-MFC-40-001",
        stock: 500, low_stock_threshold: 50,
        thumbnail: img("microfibre cleaning cloth car"),
        images: [img("microfibre cloth"),img("car cleaning"),img("car detailing"),img("auto cloth")],
        tags: ["car","cleaning","3m","automotive"],
        specifications: [{ key:"Size",value:"40 x 40 cm"},{ key:"GSM",value:"380"},{ key:"Material",value:"Microfibre"}],
        weight: 100, rating_avg: 4.5, rating_count: 680, total_sold: 2200, status: true,
      },
      {
        name: "Meguiar's Gold Class Car Wax 473ml",
        slug: toSlug("Meguiars G7516 Gold Class Car Wax 473ml"),
        short_description: "Carnauba blend, deep wet shine, UV protection",
        description: "Meguiar's Gold Class wax with Carnauba blend delivers a deep, rich wet-look shine and UV protection.",
        category_id: cat("automotive"), subcategory_id: cat("car-accessories"), brand_id: brand("meguiars"),
        price: 1499, mrp: 1999, discount_percent: 25, sku: "MEG-WAX-GC-473-001",
        stock: 120, low_stock_threshold: 15,
        thumbnail: img("car wax polish"),
        images: [img("car wax"),img("car polish shine"),img("auto detailing"),img("car care product")],
        tags: ["car-wax","meguiars","car-care","automotive"],
        specifications: [{ key:"Volume",value:"473 ml"},{ key:"Type",value:"Paste Wax"},{ key:"UV Protection",value:"Yes"}],
        weight: 550, rating_avg: 4.7, rating_count: 360, total_sold: 850, status: true,
      },
      {
        name: "Vega Crux Full Face Helmet ISI",
        slug: toSlug("Vega Crux Helmet ISI Certified"),
        short_description: "Full face, ABS shell, quick-release buckle, ISI certified",
        description: "Vega Crux full face helmet with ABS shell and ISI certification provides maximum protection for bikers.",
        category_id: cat("automotive"), subcategory_id: cat("bike-accessories"), brand_id: brand("bosch-auto"),
        price: 1299, mrp: 1799, discount_percent: 28, sku: "VEG-HLM-CRX-001",
        stock: 200, low_stock_threshold: 20,
        thumbnail: img("motorcycle helmet full face"),
        images: [img("bike helmet"),img("full face helmet"),img("motorcycle safety"),img("rider helmet")],
        tags: ["helmet","bike","vega","safety"],
        specifications: [{ key:"Type",value:"Full Face"},{ key:"Material",value:"ABS"},{ key:"Certification",value:"ISI"},{ key:"Visor",value:"Clear"}],
        weight: 1400, rating_avg: 4.4, rating_count: 580, total_sold: 1500, status: true,
      },
      {
        name: "Bosch Car Jump Starter 12V 18000mAh",
        slug: toSlug("Bosch Car Jump Starter 12V 18000mAh"),
        short_description: "18000mAh, 800A peak current, USB charging, LED torch",
        description: "Bosch portable jump starter with 18000mAh battery can start cars, bikes and act as a power bank.",
        category_id: cat("automotive"), subcategory_id: cat("car-electronics"), brand_id: brand("bosch-auto"),
        price: 3999, mrp: 5499, discount_percent: 27, sku: "BSH-JS-12V-001",
        stock: 100, low_stock_threshold: 10,
        thumbnail: img("car jump starter portable"),
        images: [img("jump starter battery"),img("car starter"),img("portable power bank car"),img("auto accessory")],
        tags: ["jump-starter","bosch","car","automotive"],
        specifications: [{ key:"Capacity",value:"18000 mAh"},{ key:"Peak Current",value:"800A"},{ key:"Voltage",value:"12V"},{ key:"USB Output",value:"5V / 2.1A"}],
        weight: 680, rating_avg: 4.6, rating_count: 290, total_sold: 560, status: true,
      },

      // ── FURNITURE ─────────────────────────────────────────────────────────
      {
        name: "IKEA POANG Armchair Oak & Beige",
        slug: toSlug("IKEA POANG Armchair Oak Beige"),
        short_description: "Bentwood frame, cushioned seat, ergonomic design",
        description: "IKEA POANG armchair with a bent layer-glued birch frame gives a comfortable, springy flexibility.",
        category_id: cat("furniture"), subcategory_id: cat("sofas-seating"), brand_id: brand("ikea"),
        price: 12999, mrp: 15999, discount_percent: 19, sku: "IKEA-POA-OAK-001",
        stock: 40, low_stock_threshold: 5, is_featured: true,
        thumbnail: img("ikea armchair living room"),
        images: [img("armchair comfortable"),img("ikea chair"),img("lounge chair"),img("living room chair")],
        tags: ["armchair","ikea","furniture","living-room"],
        specifications: [{ key:"Frame",value:"Birch Veneer"},{ key:"Cushion",value:"Foam"},{ key:"Max Load",value:"110 kg"}],
        weight: 9000, rating_avg: 4.7, rating_count: 360, total_sold: 680, status: true,
      },
      {
        name: "Wakefit Dual Comfort Mattress Queen Size",
        slug: toSlug("Wakefit Dual Comfort Mattress Queen Size"),
        short_description: "7-inch, orthopaedic + memory foam, medium-firm, 10yr warranty",
        description: "Wakefit Dual Comfort mattress combines high-density orthopaedic foam with memory foam for the perfect sleep.",
        category_id: cat("furniture"), subcategory_id: cat("beds-mattresses"), brand_id: brand("ikea"),
        price: 14999, mrp: 22999, discount_percent: 35, sku: "WKF-MTR-QN-001",
        stock: 50, low_stock_threshold: 5,
        thumbnail: img("mattress bedroom queen size"),
        images: [img("foam mattress"),img("orthopaedic mattress"),img("bed mattress"),img("wakefit mattress")],
        tags: ["mattress","wakefit","bedroom","sleep"],
        specifications: [{ key:"Size",value:"Queen (60 x 72 inch)"},{ key:"Thickness",value:"7 inch"},{ key:"Type",value:"Dual Comfort Foam"},{ key:"Warranty",value:"10 years"}],
        weight: 28000, rating_avg: 4.6, rating_count: 820, total_sold: 1500, status: true,
      },
    ]; // end products array


    // ─── Upsert all products ───────────────────────────────────────────────────
    console.log(`\nSeeding ${products.length} products...`);
    let seeded = 0;
    let skipped = 0;

    for (const product of products) {
      try {
        await Product.findOneAndUpdate(
          { slug: product.slug },
          product,
          { upsert: true, new: true }
        );
        seeded++;
      } catch (err) {
        console.warn(`⚠️  Skipped "${product.name}": ${err.message}`);
        skipped++;
      }
    }

    const total = await Product.countDocuments();
    console.log(`✅ ${seeded} products seeded${skipped ? `, ${skipped} skipped` : ""}`);
    console.log(`\n🎉 Total products in DB: ${total}`);
    process.exit(0);
  } catch (err) {
    console.error("❌ Error seeding products:", err);
    process.exit(1);
  }
}

seedProducts();
