export const IDS = {
  SLICESTATUS: {
    Idle: "idle",
    Loading: "loading",
    Succeeded: "succeeded",
    Failed: "failed",
  },
  PERMISSIONS: {
    DASHBOARD_VIEW: 1,
    USERS_LIST: 2,
    USERS_ADD: 3,
    USERS_EDIT: 4,
    USERS_DELETE: 5,
    EMPLOYEE_LIST: 6,
    EMPLOYEE_ADD: 7,
    EMPLOYEE_EDIT: 8,
    EMPLOYEE_DELETE: 9,
    ROLES_LIST: 10,
    CATEGORY_LIST: 18,
    CATEGORY_ADD: 19,
    CATEGORY_EDIT: 20,
    CATEGORY_DELETE: 21,
    BRAND_LIST: 26,
    BRAND_ADD: 27,
    PRODUCT_LIST: 30,
    PRODUCT_ADD: 31,
    PRODUCT_EDIT: 32,
    PRODUCT_DELETE: 33,
    INVENTORY_LIST: 38,
    ORDERS_LIST: 42,
    ORDERS_EDIT: 44,
    COUPONS_LIST: 47,
    COUPONS_ADD: 48,
    REVIEWS_LIST: 51,
    BANNER_LIST: 54,
    REPORTS_VIEW: 66,
    SETTINGS_VIEW: 67,
    SETTINGS_EDIT: 68,
    AUDIT_LOGS_VIEW: 87,
  },
  ORDER_STATUS: {
    pending: { label: "Pending", color: "bg-yellow-100 text-yellow-800" },
    confirmed: { label: "Confirmed", color: "bg-blue-100 text-blue-800" },
    processing: { label: "Processing", color: "bg-purple-100 text-purple-800" },
    packed: { label: "Packed", color: "bg-indigo-100 text-indigo-800" },
    shipped: { label: "Shipped", color: "bg-cyan-100 text-cyan-800" },
    out_for_delivery: { label: "Out for Delivery", color: "bg-orange-100 text-orange-800" },
    delivered: { label: "Delivered", color: "bg-green-100 text-green-800" },
    cancelled: { label: "Cancelled", color: "bg-red-100 text-red-800" },
    return_requested: { label: "Return Requested", color: "bg-pink-100 text-pink-800" },
    returned: { label: "Returned", color: "bg-gray-100 text-gray-800" },
    refunded: { label: "Refunded", color: "bg-teal-100 text-teal-800" },
  },
};
